In [1]:
# https://www.youtube.com/watch?v=QUT1VHiLmmI  21:00

In [2]:
import numpy as np

# Basics

### Array

In [3]:
a = np.array([1,2,3], dtype="int16")
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### Get Dimension

In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Dimension
b.ndim

2

### Get Shape

In [7]:
# Get Shape #(rows, cols)
a.shape

(3,)

In [8]:
# Get Shape #(rows, cols)
b.shape

(2, 3)

### Get type

In [9]:
a.dtype

dtype('int16')

In [10]:
b.dtype

dtype('float64')

### Get size

In [11]:
# Get Size # How many bytes?
a.itemsize

2

In [12]:
# Get Size # How many bytes?
b.itemsize

8

### Get Total Size

In [13]:
# Get total size # 
a.nbytes

6

## Accessing/Changing specific elements, rows, columns, etc

In [14]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Get a specific element

In [15]:
# Get a specific element [r, c]
c[1, 5]

13

In [16]:
# Get a specific element [r, c]
c[1, -2]

13

### Get a specific row

In [17]:
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

### Get a specific column

In [18]:
c[:, 2]

array([ 3, 10])

### Getting a little more fancy [startindex:endindex:stepsize]

In [19]:
c[0, 1:6:2]

array([2, 4, 6])

In [20]:
c[0, 1:-1:2]

array([2, 4, 6])

### Change an element

In [21]:
c[1,5] = 20
print(c)

print("")

# [in all row, 3rd column(2)] 
c[:,2] = 5
print(c)

print("")

c[:,2]=[1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3-d example

In [22]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Get specific element (work outside in)

In [24]:
# [from first 2d array(1 2 3 4),from second row(3 4), second element(4)] 
d[0,1,1]

4