### 16:40 https://www.youtube.com/watch?v=E1IPJOd7dWQ

In [1]:
import numpy as np

In [2]:
a = np.zeros((3,3))
a[:] = 2
print(a, "\n")
print(a.dtype)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 

float64


In [3]:
b = np.arange(1, 10).reshape((3,3))
print(b, "\n")
print(b.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

int32


## convert dtype

In [4]:
a = np.zeros((3,3), dtype=np.int64)
a[:] = 2
print(a, "\n")
print(a.dtype)

[[2 2 2]
 [2 2 2]
 [2 2 2]] 

int64


## FILL... fills the entire data structure with the given number.

In [5]:
a = np.zeros((3,3), dtype=np.int64)
a[:] = 2
a.fill(8)
print("Array A\n", a)

Array A
 [[8 8 8]
 [8 8 8]
 [8 8 8]]


## +, -, *, /

In [6]:
a = np.zeros((3,3))
a[:] = 2
a.fill(8)
a += 2
print("Array A\n", a)

Array A
 [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [7]:
a = np.zeros((3,3))
a[:] = 2
a.fill(8)
a /= 3
print("Array A\n", a)

Array A
 [[2.66666667 2.66666667 2.66666667]
 [2.66666667 2.66666667 2.66666667]
 [2.66666667 2.66666667 2.66666667]]


## Arithmetic methods

### Calculate the entire array

In [8]:
a = np.zeros((4,4))
a[:] = 2
print("Array A\n", a)
array_sum = a.sum()
print(array_sum)

Array A
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
32.0


### Calculate separately

In [9]:
# Sum of columns, (0) is axis zero
array_sum = b.sum(axis=0)
print(b, "\n")
print(array_sum)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[12 15 18]


In [10]:
# Sum of rows, (1) is axin one
array_sum = b.sum(axis=1)
print(b, "\n")
print(array_sum)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[ 6 15 24]


### multiplying all the items by one another

In [11]:
# 1*2*3*4*5*6*7*8*9 = 
array_product = b.prod()
print(b, "\n")
print(array_product)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

362880


### average

In [12]:
array_average = b.mean()
print(array_average)

5.0


### min

In [13]:
array_min = b.min()
print(array_min)

1


### max

In [14]:
array_max = b.max()
print(array_max)

9


### if we need the position

In [15]:
array_argmax, array_argmin = b.argmax(), b.argmin()
print(array_argmax, array_argmin)

8 0


### peak to peak (maxvalue - minvalue)

In [16]:
peak_to_peak = b.ptp()
print(peak_to_peak)

8


## flatten arrays

In [17]:
array_flat = b.reshape(b.size)
print(array_flat)

[1 2 3 4 5 6 7 8 9]


In [21]:
# Modifies the original array
b = np.arange(1, 10).reshape((3,3))
array_flat = b.ravel()
print(array_flat, "\n")
array_flat += 5
print(b)

[1 2 3 4 5 6 7 8 9] 

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [20]:
# makes a copy of the original array
b = np.arange(1, 10).reshape((3,3))
array_flat = b.flatten()
print(array_flat, "\n")
array_flat += 5
print(b)

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## repeat values/arrays

In [33]:
b = np.arange(1, 10).reshape((3,3))
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
array_repeat = np.repeat(255, 3)
print(array_repeat)

[255 255 255]


In [35]:
array_repeat = np.repeat(b, 3)
print(array_repeat)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9]


In [36]:
array_repeat = np.repeat(b, 3, axis=1)
print(array_repeat)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]
 [7 7 7 8 8 8 9 9 9]]


In [37]:
array_repeat = np.repeat(b, 3, axis=0)
print(array_repeat)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [7 8 9]]


In [38]:
array_unique = np.unique(array_repeat, axis=0)
print(array_unique)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Diagonal

In [40]:
array_diagonal = np.diagonal(b)
print(array_diagonal)

[1 5 9]


In [42]:
# offset=1 is 1 above the main diagonal
array_diagonal = np.diagonal(b, offset=1)
print(array_diagonal)

[2 6]


In [44]:
# offset=-1 is 1 below the main diagonal
array_diagonal = np.diagonal(b, offset=-1)
print(array_diagonal)

[4 8]


### Conversion and storage

In [45]:
my_list = b.tolist()
print("b is", type(b), "\n")
print("mylist is", type(my_list))

b is <class 'numpy.ndarray'> 

mylist is <class 'list'>
