### 13:00 https://www.youtube.com/watch?v=E1IPJOd7dWQ

In [2]:
import numpy as np

In [7]:
a = np.zeros((3,3))
a[:] = 2
print(a, "\n")
print(a.dtype)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 

float64


In [8]:
b = np.arange(1, 10).reshape((3,3))
print(b, "\n")
print(b.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

int32


## convert dtype

In [10]:
a = np.zeros((3,3), dtype=np.int64)
a[:] = 2
print(a, "\n")
print(a.dtype)

[[2 2 2]
 [2 2 2]
 [2 2 2]] 

int64


## FILL... fills the entire data structure with the given number.

In [12]:
a = np.zeros((3,3), dtype=np.int64)
a[:] = 2
a.fill(8)
print("Array A\n", a)

Array A
 [[8 8 8]
 [8 8 8]
 [8 8 8]]


## +, -, *, /

In [13]:
a = np.zeros((3,3))
a[:] = 2
a.fill(8)
a += 2
print("Array A\n", a)

Array A
 [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [16]:
a = np.zeros((3,3))
a[:] = 2
a.fill(8)
a /= 3
print("Array A\n", a)

Array A
 [[2.66666667 2.66666667 2.66666667]
 [2.66666667 2.66666667 2.66666667]
 [2.66666667 2.66666667 2.66666667]]


## Arithmetic methods

### Calculate the entire array

In [19]:
a = np.zeros((4,4))
a[:] = 2
print("Array A\n", a)
array_sum = a.sum()
print(array_sum)

Array A
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
32.0


### Calculate separately

In [30]:
# Sum of columns, (0) is axis zero
array_sum = b.sum(axis=0)
print(b, "\n")
print(array_sum)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[12 15 18]


In [33]:
# Sum of rows, (1) is axin one
array_sum = b.sum(axis=1)
print(b, "\n")
print(array_sum)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[ 6 15 24]


### multiplying all the items by one another

In [39]:
# 1*2*3*4*5*6*7*8*9 = 
array_product = b.prod()
print(b, "\n")
print(array_product)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

362880


### average

In [41]:
array_average = b.mean()
print(array_average)

5.0


### min

In [42]:
array_min = b.min()
print(array_min)

1


### max

In [43]:
array_max = b.max()
print(array_max)

9


### if we need the position

In [44]:
array_argmax, array_argmin = b.argmax(), b.argmin()
print(array_argmax, array_argmin)

8 0


### peak to peak (maxvalue - minvalue)

In [45]:
peak_to_peak = b.ptp()
print(peak_to_peak)

8


## flatten arrays

In [46]:
array_flat = b.reshape(b.size)
print(array_flat)

[1 2 3 4 5 6 7 8 9]


In [56]:
# Creates a view of the original array
b = np.arange(1, 10).reshape((3,3))
array_flat = b.ravel()
print(array_flat)
array_flat += 5
print(b)

[1 2 3 4 5 6 7 8 9]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [57]:
# makes a copy of the original array
b = np.arange(1, 10).reshape((3,3))
array_flat = b.flatten()
print(array_flat)
array_flat += 5
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
