In [5]:
import numpy as np

In [18]:
a = np.zeros((3,3))
a[:] = 2
print(a, "\n")
print(a.dtype)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 

float64


In [21]:
b = np.arange(1, 10).reshape((3,3))
print(b, "\n")
print(b.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

int32


In [22]:
a = np.zeros((3,3), dtype=np.int64)
a[:] = 2
print(a, "\n")
print(a.dtype)

[[2 2 2]
 [2 2 2]
 [2 2 2]] 

int64
